=== elielgs/chain-roteador/Core/chain/src/main/resources/processo.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="processo">
    <xs:complexType>
      <xs:sequence>
    	<xs:element ref="transacao" minOccurs="0" maxOccurs="unbounded" />
      	<xs:element ref="sequencia" minOccurs="0" maxOccurs="unbounded" />
      </xs:sequence>
      <xs:attribute name="nome" type="xs:NMTOKEN" use="required" />
      <xs:attribute name="inicio" type="xs:NMTOKEN" use="required" />
    </xs:complexType> 
  </xs:element>
  
  
  <xs:element name="transacao">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="sequencia" maxOccurs="unbounded" />
        <xs:element ref="sucesso" minOccurs="0" maxOccurs="1" />
      </xs:sequence>
      <xs:attribute name="nome" type="xs:NMTOKEN" use="required" />
    </xs:complexType> 
  </xs:element>
  
  
	<xs:element name="sucesso">
		<xs:complexType>
			<xs:attribute name="tipoRetorno">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="sequencia" />
						<xs:enumeration value="transacao" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="nomeRetorno" type="xs:NMTOKEN" />
		</xs:complexType>
	</xs:element>


  <xs:element name="resultado">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="excecao" minOccurs="0" maxOccurs="unbounded" />
      </xs:sequence>
      <xs:attribute name="tipo" type="xs:NMTOKEN" use="required" />
      <xs:attribute name="proximo" type="xs:NMTOKEN" use="optional" />
      <xs:attribute name="incluir" type="xs:NMTOKEN" use="optional" />
    </xs:complexType>
  </xs:element>

  <xs:element name="sequencia">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="resultado" minOccurs="0" maxOccurs="unbounded" />
      </xs:sequence>
      <xs:attribute name="executa" type="xs:NMTOKEN" use="optional" /> 
      <xs:attribute name="incluir" type="xs:NMTOKEN" use="optional" />
	  <xs:attribute name="proximo" type="xs:NMTOKEN" use="optional" />
	  <xs:attribute name="transacao" type="xs:NMTOKEN" use="optional" />  
    </xs:complexType>
  </xs:element>

  
  <xs:element name="excecao">
    <xs:complexType>
      <xs:attribute name="tipo" type="xs:NMTOKEN" use="required" /> 
      <xs:attribute name="construcao" type="xs:NMTOKEN" use="required" />
    </xs:complexType>
  </xs:element>
  

</xs:schema>

=== elielgs/chain-roteador/Core/chain/src/test/resources/exemploProcesso.xml
<?xml version="1.0" encoding="UTF-8" ?>
<processo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	      xsi:noNamespaceSchemaLocation="processo.xsd"
	      nome="exemploProcesso" inicio="A">
	
	
		<sequencia executa="A">
			<resultado tipo="true" proximo="B" />
			<resultado tipo="false">
				<excecao tipo="COMMAND" construcao="MN_001" />
			</resultado>
		</sequencia>
		
		<sequencia executa="B" proximo="C" />
		
		<sequencia executa="C" proximo="D" />
		
		<sequencia executa="D">
			<resultado tipo="true" proximo="E" />
			<resultado tipo="false" proximo="F" />
		</sequencia>
		
		<sequencia executa="E"/>
		<sequencia executa="F"/>
					
		
	
</processo>

=== elielgs/chain-roteador/Cep/roteador-cep-service/src/main/resources/cep/service/chain/processo/xml/processFindAPIVersionById.xml
<?xml version="1.0" encoding="UTF-8" ?>
<processo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="processo.xsd" nome="findAPIsVersionById"
	inicio="SearchAPIVersionCommand">
	
    <sequencia executa="SearchAPIVersionCommand">
		<resultado tipo="false">
            <excecao tipo="COMMAND" construcao="MN003" />
        </resultado>
       	<resultado tipo="true" proximo="CheckAPIVersionStatusParameterCommand"/>
    </sequencia>
    <sequencia executa="CheckAPIVersionStatusParameterCommand">
        <resultado tipo="true" proximo="FilterAPIVersionStatusCommand"/>
   	</sequencia>
   	<sequencia executa="FilterAPIVersionStatusCommand" />
</processo>

=== elielgs/chain-roteador/Cep/roteador-cep-service/src/main/resources/cep/service/chain/processo/xml/processFindAPIById.xml
<?xml version="1.0" encoding="UTF-8" ?>
<processo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="processo.xsd" nome="findAPIById"
	inicio="SearchAPIsListCommand">
	

    <sequencia executa="SearchAPIsListCommand" proximo="SelectAPIFromAPIListCommand"/>
    <sequencia executa="SelectAPIFromAPIListCommand" >
    <resultado tipo="true" proximo="SearchAPIVersionCommand"/>
        <resultado tipo="false">
            <excecao tipo="COMMAND" construcao="MN000" />
        </resultado>
     </sequencia>
     <sequencia executa="SearchAPIVersionCommand" proximo="SearchAPIVersionDocumentationCommand"/>
 	<sequencia executa="SearchAPIVersionDocumentationCommand" proximo="BuildJSONReturnCommand"/>
 	<sequencia executa="BuildJSONReturnCommand"/>
</processo>

=== elielgs/chain-roteador/Cep/roteador-cep-service/src/main/resources/service/chain/processo/xml/processFindDocByAPIVersion.xml
<?xml version="1.0" encoding="UTF-8" ?>
<processo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		  xsi:noNamespaceSchemaLocation="processo.xsd" nome="findDocsByVersion"
		  inicio="SearchAPIVersionDocumentationCommand">

	<sequencia executa="SearchDocumentationVersionCommand">
		<resultado tipo="false">
			<excecao tipo="COMMAND" construcao="MN004" />
		</resultado>
		<resultado tipo="true" proximo="SearchAPIVersionDocumentationCommand"/>
	</sequencia>

	<sequencia executa="SearchAPIVersionDocumentationCommand">
		<resultado tipo="false">
			<excecao tipo="COMMAND" construcao="MN004" />
		</resultado>
	</sequencia>
</processo>
